import type {
  FormInfo,
  PermissionRequest,
  SessionExecutionFailed,
  SessionInfo,
  SessionStatus,
} from "@opencode-ai/client"

export type AgentlineAgentID = `agt_${string}`

/**
 * Agentline presents one readable agent status. OpenCode contributes its
 * exact session states; the remaining states describe Agentline's attachment
 * to OpenCode. They do not describe submission or task progress.
 */
export type AgentlineAgentStatus =
  | SessionStatus["type"]
  | "unattached"
  | "attaching"
  | "loading"
  | "unavailable"

/**
 * A resolved reference carries the stable identity and its current language
 * name. Names may change later; IDs do not.
 */
export type AgentlineAgentRef = {
  id: AgentlineAgentID
  name: string
  description?: string
  sessionID?: SessionInfo["id"]
}

/**
 * Agentline reduces OpenCode permission, question, and error data into a
 * readable UI notice while retaining the original typed OpenCode payload.
 */
export type AgentlineAttention =
  | {
      kind: "permission"
      requests: readonly PermissionRequest[]
      summary: string
    }
  | {
      kind: "form"
      requests: readonly FormInfo[]
      summary: string
    }
  | {
      kind: "error"
      error: SessionExecutionFailed["data"]["error"]
      summary: string
    }

/**
 * The combined read model consumed by Agentline's UI. Agentline owns the
 * identity and coordination fields; session metadata is observed from
 * OpenCode and therefore uses OpenCode's exported types directly.
 */
export type AgentlineAgent = {
  ref: AgentlineAgentRef
  title?: SessionInfo["title"]
  directory?: SessionInfo["location"]["directory"]
  status: AgentlineAgentStatus
  latestAssignment?: string
  attention?: AgentlineAttention
  updatedAt?: SessionInfo["time"]["updated"]
}

export type AgentlineBoard = {
  agents: readonly AgentlineAgent[]
  focusedAgentID?: AgentlineAgentID
  selectedAgentID?: AgentlineAgentID
}

/**
 * The state of Agentline's submission call for one target. This is deliberately
 * separate from evidence that OpenCode admitted the message.
 */
export type AgentlineSubmissionStatus =
  | "submitting"
  | "submitted"
  | "failed"

export type AgentlineSubmissionActivity =
  | Readonly<{ status: "submitting" }>
  | Readonly<{ status: "submitted" }>
  | Readonly<{ status: "failed"; error: string }>

/**
 * Durable evidence that the intended destination accepted this dispatch.
 * OpenCode queue and execution state remain owned by OpenCode.
 */
export type AgentlineDispatchReceipt =
  | Readonly<{ kind: "local" }>
  | Readonly<{ kind: "opencode" }>

type AgentlineDispatchTargetBase = {
  /** Stable identity; name is only the alias snapshot shown in history. */
  agentID: AgentlineAgentID
  name: string
  /** Result of Agentline's submission call, independent of the receipt. */
  submission: AgentlineSubmissionActivity
}

/** Delivery record for one agent in a potentially multi-agent dispatch. */
export type AgentlineDispatchTargetActivity =
  | (AgentlineDispatchTargetBase & {
      destination: Readonly<{ kind: "local" }>
      receipt: Readonly<{ kind: "local" }>
    })
  | (AgentlineDispatchTargetBase & {
      destination: Readonly<{
        kind: "opencode"
        sessionID: SessionInfo["id"]
        /** Preassigned ID used to obtain or recover the exact receipt. */
        messageID: string
      }>
      /** Absent until exact OpenCode admission is confirmed. */
      receipt?: Readonly<{ kind: "opencode" }>
    })

/** One user send action. Each target is submitted and updated independently. */
export type AgentlineDispatchActivity = {
  id: string
  kind: "dispatch"
  message: string
  targets: AgentlineDispatchTargetActivity[]
  createdAt: number
}

/** A notice generated by Agentline itself, not an OpenCode system event. */
export type AgentlineSystemActivity = {
  id: string
  kind: "system"
  level: "info" | "success" | "error"
  message: string
  createdAt: number
}

export type AgentlineActivity =
  | AgentlineDispatchActivity
  | AgentlineSystemActivity

export type AgentlineState = {
  version: 5
  agents: Record<AgentlineAgentID, AgentlineAgentRef>
  /** Durable history in chronological order: oldest first, newest last. */
  activity: AgentlineActivity[]
}
